apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo2410
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo2410
  template:
    metadata:
      labels:
        app: demo2410
    spec:
      containers:
        - name: demo2410
          image: ghcr.io/dsanchor/demo2410:$IMAGE_TAG
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo2410
spec:
  selector:
    app: demo2410
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer